language: cpp

cache: ccache

compiler:
- gcc

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-6

install:
- "[ $CC = gcc ] && export CC=gcc-6 || true"
- "[ $CXX = g++ ] && export CXX=g++-6 || true"

script:
- mkdir -p build && cd build && cmake .. && make && make test

notifications:
  email:
    on_success: never
    on_failure: never
  slack:
    secure: KX+nen5l31Vbe2Lt132V3DF/S1Zxy+3LFOJ11SJl2YJGC+fSVmfRgzdrMDqlKHUEzIBNbtnmpANXylTEpcYClHfxU2MesNpgSfJTCMb8HiKIR5QkxKzaOR90bXBz5dHmuf+Dx+w63pAXqcIf66nH594ef8hEWqSlaclKYjwn0vSaUVCc9/vNhcx5sNqoypN7S+tYe5pFiXrx+Le1lQH6vT26aGKvHfxPTy/bMQGTl7ZulgQ1sZYvH07pSjiFUfBQ8tZxYOTUTb0u2h4DnuAIn1Yo5jo0JqgbwMqH9WRsSThVxyBUeiYGHMUV3JB6NSOQIhH7frPKK9HOc7eseGrcdCoYqsGdOLiTehH8VyN5IvNTA0PoKH5B7Z7G5m3oOXDmTCRvrWudfxWDW1Zi5X3/TWBgMFFBlWn4mlFEx5wNqoQytdGHYxEORl9yIZf12IsssLxIm7Ubd3uWw7VWpuiPSoKN/tt+y3Jxt9UGvd1rCGz2V6mFxoPGuYahjlB7YlFM6rIb1QYYZoSq8HR0ijqwezZX6VSIRWR6Zej6WYQuMi/Abe8Jqiw1/F1OBkJfpX/o0cs9uI2pTlLnEXYZkJwoyHmJbIl8rdMDncByWGZnm1ijfTbQq2t+zxNkT5XvP5QFQTRdDP0dqFbfkem7bHQIAWJvr6IqNkgK4BwERUzuwLw=
